site_name: Biết là
theme:
  name: material
  language: vi
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections

plugins:
  - tags
  - search
#  - search.suggest
#  - search.share
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
